### ISSUE TITLE
"using MuJoCo"  LoadError: UndefVarError: Cvoid not defined

### ISSUE THREAD

**Issue by wuweijia1994** [klowrey/MuJoCo.jl#5]
Hi, I am using MuJoCo in OSX with Julia-v0.6.4. Before it worked well but today after I update the packages with "Pkg.update()",  it first has an error with not finding the "Libdl" module. Then I fix it by changing the "using Libdl"  to "using Base.Libdl" in the MuJoCo.jl. However, now it has another bug as followed:

![image](https://user-images.githubusercontent.com/9395444/44319732-85fa8100-a3f2-11e8-9dc9-9e6c399bf596.png)

**Comment by klowrey** [comment]
Yes that is from an eventual transition over to julia 1.0.

If you do a checkout of the 0.6 branch

```
Pkg.checkout("MuJoCo", "0.6")
Pkg.build("MuJoCo")
```

that should resolve it until you're ready to move to Julia 1.0

**Comment by wuweijia1994** [comment]
It still does not work. “ERROR: MuJoCo is dirty, bailing”

So I turn to upgrade Julia to 1.0
And the following is some bugs I fixed in the "deps/build.jl".
1. add "using Libdl"
2. change "is_linux()" to "Sys.islinux()" / "is_apple()" to "Sys.isapple()" / "is_windows()" to "Sys.iswindows()"
3. change "info()" function to "println()"

And then it works perfectly.
